// lang-es.ts

export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'hello_world': 'hola mundo',
    'Home': 'Beranda',
    'Profile': 'Profil',
    'Contact Tri': 'Hubungi tri',
    'Settings': 'Pengaturan',
    'Notification': 'Notifikasi',
    'Log Out': 'Keluar',
    'Your Tri Number': 'Nomor Tri Kamu',
    'Main Balance': 'Pulsa Utama',
    'Credit Balance': 'Saldo Kredit',
    'Remaining Credit': 'Sisa Kredit',
    'Validity': 'Sisa masa berlaku',
    'Payment Due Date': 'Jatuh Tempo Pembayaran',
    'Package': 'Paket',
    'TRIms Balance': 'Saldo TRIms',
    'Bill': 'Tagihan',
    'Reload': 'Isi Ulang',
    'Enter the voucher code': 'Masukkan kode voucher',
    'Remaining Credit Limit': 'Sisa Batas kredit',
    'Credit': 'Kredit',
    'Payment': 'Pembayaran',
    'PAY': 'BAYAR',
    'Save': 'Save',
    'Bill_Due_Date': 'Bill Due Date',
    'Periode': 'Periode',
    'Details': 'Details',
    'Sub_Total': 'Sub Total',
    'Recommended_For_You': 'Direkomendasikan_untukmu',
    'Select Language': 'Pilih Bahasa',
    'Language' : 'Bahasa',
    'Leave a Message': 'Tinggalkan Pesan',
    'Paid Bill': 'Tagihan Terbayar',
    'Total Credit Limit': 'Total Batas Kredit',
    'Previous Bill': 'Tagihan Sebelumnya',
    'Current Bill': 'Tagihan Sekarang',
    'Status': 'Status',
    'Bill Summary': 'Rincian Tagihan',
    'Remaining Quota': 'Sisa Kuota',
    'Enter_the_Voucher_code': 'Masukkan_kode_voucher',
    'Payment Method': 'Metode pembayaran',
    'Submit': 'Kirim',
    'Confirmation, you will purchase.': 'Konfirmasi, Anda akan membeli.',
    'Package Name': 'Nama paket',
    'Price': 'Harga',
    'Click Buy, if you want to use one-time transaction. or click Next, if you will/have registered your credit card.': 'Klik Beli, jika Anda ingin menggunakan transaksi satu kali. atau klik Next, jika Anda mau / telah mendaftarkan kartu kredit Anda.',
    'Buy': 'Membeli',
    'Welcome to 3Care, Please login.': 'Selamat datang di 3Care, silahkan masuk.',
    'Name': 'Nama',
    'See All': 'Lihat semua',
    'Thanks you for purchasing': 'Terima kasih sudah beli',
    'CONTINUE': 'TERUS',
    'Contact Person': 'Orang yang dapat dihubungi',
    'Service Type': 'Tipe Layanan',
    'Reply Via': 'Balas Via',
    'Message Title': 'Judul pesan',
    'Message Content': 'Isi pesan',
    'Choose your service': 'Pilih Paket Berlanggananmu',
    'Provider': 'Pemberi',
    'Next': 'Berikutnya',
    'Thank You': 'Terima kasih',
    'Thank you, your transaction has been processed.': 'Terimakasih, transaksi anda telah diproses.',
    'Please send sms through bima plus.': 'Silahkan kirim sms melalui bima plus.',
    'Please login using Tri number': 'Silahkan login menggunakan nomor Tri',
    'Sorry': 'Maaf',
    'Product not found': 'Produk tidak ditemukan',
    'Number': 'Nomor',
    'Last Bill': 'Tagihan Terakhir',
    'Over Payment': 'kelebihan Pembayaran',
    'Bill Total': 'Total Tagihan',
    'PAY ALL': 'BAYAR SEMUA',
    'This product can be purchased through bima + application': 'Product ini dapat dibeli melalui aplikasi bima+',
    'BILL SUMMARY': 'RINCIAN TAGIHAN',
    'Customer Satisfaction Survey': 'Survei Kepuasan Pelanggan',
    'Your Problem Solved?': 'Masalah Anda Dipecahkan?',
    'Give feedback for this service, so we can do better': 'Berikan umpan balik untuk layanan ini, jadi kita bisa berbuat lebih baik',
    'How would you rate this service': 'Bagaimana Anda menilai layanan ini?',
    'Yes': 'Ya',
    'No': 'Tidak',
    'Another solution suggested': 'Solusi lain telah diberikan',
    'Very Good': ' Sangat Baik',
    'Good': 'Baik',
    'Average': 'Rata-rata',
    'Below Average': 'Dibawah Rata-rata',
    'Bad': 'Sangat Kurang',
    'Welcome to 3Chat, Can we help you?': 'Selamat datang di 3Chat, Ada yang bisa kami bantu?',
    'Are you sure want to end the chat session?': 'Apakah kamu yakin ingin mengakhiri sesi pembicaraan?',
    'Month': 'Month',
    'This Month Bill': '',
    'Outstanding Bill': '',
    'Due Date': '',
    'More' : 'Lebih Lengkap',
    'Ok' : 'Baik',
    'Your Chat Session has been closed by the agent. Please log back in.' : 'Sesi Obrolan Anda telah di tutup oleh agen. silahkan masuk kembali.',
    'Complaint' : 'Pengaduan',
    'Inquiry' : 'Pertanyaan',
    'Thank You for Feedback': 'Terimakasih untuk kritik/saran anda',
    'Thank you, your transaction ': 'Terima Kasih, Transaksi ',
    '...More': '...Lebih',
    '...Less': '...Kurangi',
    ' has been processed.': ' kamu sedang diproses.' ,
    'Are you sure want to change the Language?':'Apakah Anda yakin ingin mengubah Bahasa?',
    'Langauge changed successfully':'Langauge berhasil berubah'
};
