// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'hello_world': 'hello world',
    'Home': 'Home',
    'Profile': 'Profile',
    'Contact Tri': 'Contact Tri',
    'Settings': 'Settings',
    'Notification': 'Notification',
    'Log Out': 'Log Out',
    'Your Tri Number': 'Your Tri Number',
    'Main Balance': 'Main Balance',
    'Credit Balance': 'Credit Balance',
    'Remaining Credit': 'Remaining Credit',
    'Validity': 'Validity',
    'Payment Due Date': 'Payment Due Date',
    'Package': 'Package',
    'TRIms Balance': 'TRIms Balance',
    'Bill': 'Bill',
    'Reload': 'Reload',
    'Enter the voucher code': 'Enter the voucher code',
    'Remaining Credit Limit': 'Remaining Credit Limit',
    'Credit': 'Credit',
    'Payment': 'Payment',
    'PAY': 'PAY',
    'Save': 'Save',
    'Bill_Due_Date': 'Bill Due Date',
    'Periode': 'Periode',
    'Details': 'Details',
    'Sub_Total': 'Sub_Total',
    'Recommended_For_You': 'Recommended_For_You',
    'Select Language': 'Select Language',
    'Language': 'Language',
    'Leave a Message': 'Leave a Message',
    'Paid Bill': 'Paid Bill',
    'Total Credit Limit': 'Total Credit Limit',
    'Previous Bill': 'Previous Bill',
    'Current Bill': 'Current Bill',
    'Status': 'Status',
    'Bill Summary': 'Bill Summary',
    'Remaining Quota': 'Remaining Quota',
    'Enter_the_Voucher_code': 'Enter_the_Voucher_code',
    'Payment Method': 'Payment Method',
    'Submit': 'Submit',
    'Confirmation, you will purchase.': 'Confirmation, you will purchase.',
    'Package Name': 'Package Name',
    'Price': 'Pricev',
    'Click Buy, if you want to use one-time transaction. or click Next, if you will/have registered your credit card.': 'Click Buy, if you want to use one-time transaction. or click Next, if you will/have registered your credit card.',
    'Buy': 'Buy',
    'Welcome to 3Care, Please login.': 'Welcome to 3Care, Please login.',
    'Name': 'Name',
    'See All': 'See All',
    'Thanks you for purchasing': 'Thanks you for purchasing',
    'CONTINUE': 'CONTINUE',
    'Contact Person': 'Contact Person',
    'Service Type': 'Service Type',
    'Reply Via': 'Reply Via',
    'Message Title': 'Message Title',
    'Message Content': 'Message Content',
    'Choose your service': 'Choose your service',
    'Provider': 'Provider',
    'Next': 'Next',
    'Thank You': 'Thank You',
    'Thank you, your transaction has been processed.': 'Thank you, your transaction has been processed.',
    'Please send sms through bima plus.': 'Please send sms through bima plus.',
    'Please login using Tri number': 'Please login using Tri number',
    'Sorry': 'Sorry',
    'Product not found': 'Product not found',
    'Number': 'Number',
    'Last Bill': 'Last Bill',
    'Over Payment': 'Over Payment',
    'Bill Total': 'Bill Total',
    'PAY ALL': 'PAY ALL',
    'This product can be purchased through bima + application': 'This product can be purchased through bima + application',
    'BILL SUMMARY': 'BILL SUMMARY',
    'Customer Satisfaction Survey': 'Customer Satisfaction Survey',
    'Your Problem Solved?': 'Your Problem Solved?',
    'Give feedback for this service, so we can do better': 'Give feedback for this service, so we can do better',
    'How would you rate this service': 'How would you rate this service',
    'Yes': 'Yes',
    'No': 'No',
    'Another solution suggested': 'Another solution suggested',
    'Very Good': 'Very Good',
    'Good': 'Good',
    'Average': 'Average',
    'Below Average': 'Below Average',
    'Bad': 'Bad',
    'Welcome to 3Chat, Can we help you?': 'Welcome to 3Chat, Can we help you?',
    'Are you sure want to end the chat session?': 'Are you sure want to end the chat session?',
    'Month': 'Month',
    'This Month Bill': 'This Month Bill',
    'Outstanding Bill': 'Outstanding Bill',
    'Due Date': 'Due Date',
    'More': 'More',
    'Ok': 'Ok',
    'Your Chat Session has been closed by the agent. Please log back in.': 'Your Chat Session has been closed by the agent. Please log back in.',
    'Complaint': 'Complaint',
    'Inquiry': 'Inquiry',
    'Thank You for Feedback': 'Thank You for Feedback',
    'Thank you, your transaction ' : 'Thank you, your transaction ',
    '...More': '...More',
    '...Less': '...Less',
    ' has been processed.': ' has been processed.',
    'Are you sure want to change the Language?':'Are you sure want to change the Language?',
    'Langauge changed successfully':'Langauge changed successfully'
    
};
